//
//  UsersController.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface UsersController : BaseController

/**
* Completion block definition for asynchronous call to Authentications */
typedef void (^CompletedGetAuthentications)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Allow clients to test authentication.
*/
- (void) getAuthenticationsWithCompletionBlock:(CompletedGetAuthentications) onCompleted;

@end