//
//  Account.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_ACCOUNT
#define APIMATIC_ACCOUNT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Account
@end

@interface Account : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* contactNumber;

/**
* TODO: Write general description for this field
*/
@property NSString* email;

/**
* TODO: Write general description for this field
*/
@property NSString* firstname;

/**
* TODO: Write general description for this field
*/
@property NSString* lastname;

/**
* TODO: Write general description for this field
*/
@property NSString* number;

/**
* TODO: Write general description for this field
*/
@property NSArray* roles;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif