//
//  CallerLocation.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "CallerLocation.h"

@implementation CallerLocation

/**
* Address
*/
@synthesize address;

/**
* City
*/
@synthesize city;

/**
* Country Name
*/
@synthesize country;

/**
* Location Name
*/
@synthesize name;

/**
* Postal Code
*/
@synthesize postalCode;

/**
* Region
*/
@synthesize region;

/**
* Unit Number
*/
@synthesize unitNumber;

/**
* Unit Type
*/
@synthesize unitType;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"address": @"address",
        @"city": @"city",
        @"country": @"country",
        @"name": @"name",
        @"postal_code": @"postalCode",
        @"region": @"region",
        @"unit_number": @"unitNumber",
        @"unit_type": @"unitType"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end