//
//  CallerLocation.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_CALLERLOCATION
#define APIMATIC_CALLERLOCATION

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CallerLocation
@end

@interface CallerLocation : JSONModel

/**
* Address
*/
@property NSString* address;

/**
* City
*/
@property NSString* city;

/**
* Country Name
*/
@property NSString* country;

/**
* Location Name
*/
@property NSString* name;

/**
* Postal Code
*/
@property int postalCode;

/**
* Region
*/
@property NSString* region;

/**
* Unit Number
*/
@property int unitNumber;

/**
* Unit Type
*/
@property NSString* unitType;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif