//
//  CartCheckoutForm.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_CARTCHECKOUTFORM
#define APIMATIC_CARTCHECKOUTFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Checkout.h"


//protocol defined for deserialization of JSON
@protocol CartCheckoutForm
@end

@interface CartCheckoutForm : JSONModel

/**
* TODO: Write general description for this field
*/
@property Checkout* checkout;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif