//
//  Data.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "Data.h"

@implementation Data

/**
* TODO: Write general description for this method
*/
@synthesize limit;

/**
* TODO: Write general description for this method
*/
@synthesize page;

/**
* TODO: Write general description for this method
*/
@synthesize results;

/**
* TODO: Write general description for this method
*/
@synthesize total;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"limit": @"limit",
        @"page": @"page",
        @"results": @"results",
        @"total": @"total"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end