//
//  LocationItem.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_LOCATIONITEM
#define APIMATIC_LOCATIONITEM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Item.h"
#import "CallerLocation.h"


//protocol defined for deserialization of JSON
@protocol LocationItem
@end

@interface LocationItem : Item

/**
* TODO: Write general description for this field
*/
@property CallerLocation* callerLocation;

/**
* TODO: Write general description for this field
*/
@property NSString* attributes;

/**
* TODO: Write general description for this field
*/
@property NSString* didTypeHandle;

/**
* TODO: Write general description for this field
*/
@property NSString* locationHandle;

/**
* TODO: Write general description for this field
*/
@property int quantity;

/**
* TODO: Write general description for this field
*/
@property int trunkId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif