//
//  LocationItem.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "LocationItem.h"

@implementation LocationItem

/**
* TODO: Write general description for this method
*/
@synthesize callerLocation;

/**
* TODO: Write general description for this method
*/
@synthesize attributes;

/**
* TODO: Write general description for this method
*/
@synthesize didTypeHandle;

/**
* TODO: Write general description for this method
*/
@synthesize locationHandle;

/**
* TODO: Write general description for this method
*/
@synthesize quantity;

/**
* TODO: Write general description for this method
*/
@synthesize trunkId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"_caller_location": @"callerLocation",
        @"attributes": @"attributes",
        @"did_type_handle": @"didTypeHandle",
        @"location_handle": @"locationHandle",
        @"quantity": @"quantity",
        @"trunk_id": @"trunkId"  
    }];
    [map addEntriesFromDictionary: [super keyMap]];   

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end