//
//  TelephoneNumber.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "TelephoneNumber.h"

@implementation TelephoneNumber

/**
* TODO: Write general description for this method
*/
@synthesize routing;

/**
* TODO: Write general description for this method
*/
@synthesize alias;

/**
* TODO: Write general description for this method
*/
@synthesize channels;

/**
* TODO: Write general description for this method
*/
@synthesize sipEndPointUri;

/**
* TODO: Write general description for this method
*/
@synthesize trunkId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"_routing": @"routing",
        @"alias": @"alias",
        @"channels": @"channels",
        @"sip_end_point_uri": @"sipEndPointUri",
        @"trunk_id": @"trunkId"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end