//
//  TelephoneNumber.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_TELEPHONENUMBER
#define APIMATIC_TELEPHONENUMBER

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "RoutingBase.h"


//protocol defined for deserialization of JSON
@protocol TelephoneNumber
@end

@interface TelephoneNumber : JSONModel

/**
* TODO: Write general description for this field
*/
@property RoutingBase* routing;

/**
* TODO: Write general description for this field
*/
@property NSString* alias;

/**
* TODO: Write general description for this field
*/
@property int channels;

/**
* TODO: Write general description for this field
*/
@property NSString* sipEndPointUri;

/**
* TODO: Write general description for this field
*/
@property int trunkId;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif