//
//  TelephoneNumberForm.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_TELEPHONENUMBERFORM
#define APIMATIC_TELEPHONENUMBERFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "TelephoneNumber.h"


//protocol defined for deserialization of JSON
@protocol TelephoneNumberForm
@end

@interface TelephoneNumberForm : JSONModel

/**
* TODO: Write general description for this field
*/
@property TelephoneNumber* telephoneNumber;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif