//
//  TrunkItem.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "TrunkItem.h"

@implementation TrunkItem

/**
* TODO: Write general description for this method
*/
@synthesize routing;

/**
* TODO: Write general description for this method
*/
@synthesize attributes;

/**
* TODO: Write general description for this method
*/
@synthesize channels;

/**
* TODO: Write general description for this method
*/
@synthesize sipUri;

/**
* TODO: Write general description for this method
*/
@synthesize trunkHandle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"_routing": @"routing",
        @"attributes": @"attributes",
        @"channels": @"channels",
        @"sip_uri": @"sipUri",
        @"trunk_handle": @"trunkHandle"  
    }];
    [map addEntriesFromDictionary: [super keyMap]];   

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end