//
//  TrunkItem.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef APIMATIC_TRUNKITEM
#define APIMATIC_TRUNKITEM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Item.h"
#import "Routing.h"


//protocol defined for deserialization of JSON
@protocol TrunkItem
@end

@interface TrunkItem : Item

/**
* TODO: Write general description for this field
*/
@property Routing* routing;

/**
* TODO: Write general description for this field
*/
@property NSString* attributes;

/**
* TODO: Write general description for this field
*/
@property int channels;

/**
* TODO: Write general description for this field
*/
@property NSString* sipUri;

/**
* TODO: Write general description for this field
*/
@property NSString* trunkHandle;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif