//
//  Configuration.m
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#import "Configuration.h"

@implementation Configuration

/** The base Uri for API calls */
+(NSString*) BaseUri
{
    return @"https://api.magictelecom.com/app_dev.php";
}

/** API Token */
+(NSString*) XAuthToken
{
    return @"123abcqwerty";
}


@end