//
//  Configuration.h
//  MagicTelecomAPI
//
//  This file was automatically generated by APIMATIC v2.0 on 06/23/2016
//
#ifndef MagicTelecomAPI_Configuration_h
#define MagicTelecomAPI_Configuration_h

@interface Configuration : NSObject

/** The base Uri for API calls */
+(NSString*) BaseUri;

/** API Token */
+(NSString*) XAuthToken;


@end

#endif
